# Generated by Django 3.1.1 on 2021-01-31 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updown', '0003_auto_20210201_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='picture',
        ),
    ]
