# Generated by Django 3.1.1 on 2021-02-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updown', '0004_remove_book_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('Enrollment_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('St_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
