# Generated by Django 3.1.1 on 2021-02-21 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updown', '0005_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
